package com.sap.exciseduty.entities;

public interface IMaterialMasterExtension {

    public static final String NAME = "MaterialMasterExtension";

    public static final String KEY_ELEMENT_MATERIAL_NUMBER = "MATERIALNUMBER";
    public static final String KEY_ELEMENT_COMPANY_CODE = "COMPANYCODE";
    public static final String KEY_ELEMENT_EXCISE_DUTY_TYPE_ID = "EXCISEDUTYTYPEID";

    public static final String ELEMENT_EXCISE_DUTY_PROCUREMENT_INDICATOR = "EXCISEDUTYPROCUREMENTINDICATOR";
    public static final String ELEMENT_TAX_WAREHOUSE_REGISTRATION_MANUFACTORING_PLANT = "TAXWAREHOUSEREGISTRATIONOFMANUFACTURINGPLANT";
    public static final String ELEMENT_EXCISE_DUTY_NUMBER_FOR_TAX_WAREHOUSE = "EXCISEDUTYNUMBERFORTAXWAREHOUSE";
    public static final String ELEMENT_EXCISE_DUTY_TYPE_INDEPENDENT_MATERIAL_GROUP = "EXCISEDUTYTYPEINDEPENDENTMATERIALGROUP";
    public static final String ELEMENT_ALKOHOLOC_STRENGTH = "ALCOHOLICSTRENGTH";
    public static final String ELEMENT_VALID_FROM = "VALIDFROM";

}
