package com.sap.exciseduty.entities;

public interface IStockLedgerLineItem {

    public static final String NAME = "StockLedgerLineItem";

    public static final String KEY_ELEMENT_MATERIAL_DOCUMENT_YEAR = "MATERIALDOCUMENTYEAR";
    public static final String KEY_ELEMENT_MATERIAL_DOCUMENT_NUMBER = "MATERIALDOCUMENTNUMBER";
    public static final String KEY_ELEMENT_MATERIAL_DOCUMENT_ITEM = "MATERIALDOCUMENTITEM";
    public static final String KEY_ELEMENT_EXCISE_DUTY_POSITION_NUMBER = "EXCISEDUTYPOSITIONNUMBER";
    public static final String KEY_ELEMENT_EXCISE_DUTY_TYPE_ID = "EXCISEDUTYTYPEID";
    public static final String ELEMENT_COMPANY_CODE = "COMPANYCODE";
    public static final String ELEMENT_TAX_WAREHOUSE_REGISTRATION = "TAXWAREHOUSEREGISTRATION";
    public static final String ELEMENT_PLANT = "PLANT";
    public static final String ELEMENT_STORAGE_LOCATION = "STORAGELOCATION";
    public static final String ELEMENT_MATERIAL_DOCUMENT_POSTING_DATE = "MATERIALDOCUMENTPOSTINGDATE";
    public static final String ELEMENT_STOCK_LEDGER_NUMBER = "STOCKLEDGERNUMBER";
    public static final String ELEMENT_NO_ENTRY_IN_EXTENDED_STOCK_LEDGER = "NOENTRYINEXTENDEDSTOCKLEDGER";
    public static final String ELEMENT_MATERIAL_NUMBER = "MATERIALNUMBER";
    public static final String ELEMENT_BATCH_NUMBER = "BATCHNUMBER";
    public static final String ELEMENT_QUANTITY = "QUANTITY";
    public static final String ELEMENT_BASE_UNIT_OF_MEASURE = "BASEUNITOFMEASURE";
    public static final String ELEMENT_ED_MOVEMENT_CATEGORY_ID = "EDMOVEMENTCATEGORYID";
    public static final String ELEMENT_ERP_MOVEMENT_TYPE = "ERPMOVEMENTTYPE";
    public static final String ELEMENT_STOCK_LEDGER_GROUPE_ID = "STOCKLEDGERGROUPID";
    public static final String ELEMENT_STOCK_LEDGER_DEVISION = "STOCKLEDGERDIVISION";
    public static final String ELEMENT_STOCK_LEDGER_SUBDIVISION = "STOCKLEDGERSUBDIVISION";
    public static final String ELEMENT_ALCOHOLIG_STRENGHT = "ALCOHOLICSTRENGTH";
    public static final String ELEMENT_TAX_WAREHOUSE_REGISTRATION_OF_MANUFACTURING_PLANT = "TAXWAREHOUSEREGISTRATIONOFMANUFACTURINGPLANT";
    public static final String ELEMENT_EXCISE_DUTY_NUMBER_FOR_TAX_WAREHOUSE = "EXCISEDUTYNUMBERFORTAXWAREHOUSE";
    public static final String ELEMENT_EXTERNAL_TAX_WAREHOUSE_REGISTRATION = "EXTERNALTAXWAREHOUSEREGISTRATION";
    public static final String ELEMENT_EXTERNAL_EXCISE_DUTY_NUMBER = "EXTERNALEXCISEDUTYNUMBER";
    public static final String ELEMENT_SALES_ORDER_NUMBER = "SALESORDERNUMBER";
    public static final String ELEMENT_SALES_ORDER_ITEM = "SALESORDERITEM";
    public static final String ELEMENT_EXCISE_DUTY_PROCUREMENT_INDICATOR = "EXCISEDUTYPROCUREMENTINDICATOR";
    public static final String ELEMENT_ACCOUNTING_JOURNAL_REFERENCE = "ACCOUNTINGJOURNALREFERENCE";
    public static final String ELEMENT_TAX_VALUE_AMOUNT = "TAXVALUEAMOUNT";
    public static final String ELEMENT_TAX_VALUE_CURRENCY = "TAXVALUECURRENCY";
}
